spring:
  application:
    name: users-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


server:
  port: 8081

jwt:
  secret:
  expiration: 86400000              # 24 hours
  refresh-expiration: 604800000     # 7 days

aws:
  access-key:
  secret-key:
  region:
  s3:
    bucket-name:

management:
  endpoints:
    web:
      exposure:
        include: health,info







