spring:
  application:
    name: post-service

  datasource:
    url: jdbc:myqsl://locahost:3306/post_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name:  com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


server:
  port: 8082

aws:
  access-key:
  secret-key:
  region:
  s3:
    bucket-name:

management:
  endpoints:
    web:
      exposure:
        include: health,info
